[workspace]
resolver = "2"
members = ["solari", "solari-cli", "solari-dmfr", "solari-export-graph", "solari-geomath", "solari-server", "solari-spatial", "solari-test", "solari-transfers"]

[profile.release-debug]
inherits = "release"
debug = true
